//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class localEntities1 : DbContext
    {
        public localEntities1()
            : base("name=localEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<producto> producto { get; set; }
    }
}
